module.exports = {
  APARTMENT_NOT_FOUND_FOR_INVOICE: "APARTMENT_NOT_FOUND_FOR_INVOICE",
  NO_ACTIVE_UTILITY_METERS: "NO_ACTIVE_UTILITY_METERS",
  NO_ACTIVE_PRICING_FOR_METER_TYPE: "NO_ACTIVE_PRICING_FOR_METER_TYPE",
  INVALID_METER_READING_CONSUMPTION: "INVALID_METER_READING_CONSUMPTION",
  NO_METER_READINGS_FOR_PERIOD: "NO_METER_READINGS_FOR_PERIOD",
  NO_BILLABLE_ITEMS_FOR_INVOICE: "NO_BILLABLE_ITEMS_FOR_INVOICE",
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  INVOICE_NOT_CANCELLED_FOR_RESTORE: "INVOICE_NOT_CANCELLED_FOR_RESTORE",
};
