/** Mã lỗi cố định — FE log Console / map i18n */
module.exports = {
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  INVALID_PAYMENT_AMOUNT: "INVALID_PAYMENT_AMOUNT",
  PAYMENT_ALREADY_FINALIZED: "PAYMENT_ALREADY_FINALIZED",
  PAYMENT_NOT_PENDING_FOR_QR: "PAYMENT_NOT_PENDING_FOR_QR",
  VIETQR_CONFIG_INVALID: "VIETQR_CONFIG_INVALID",
  CASSO_NOT_CONFIGURED: "CASSO_NOT_CONFIGURED",
  CASSO_INVALID_SECRET: "CASSO_INVALID_SECRET",
  CASSO_INVALID_PAYLOAD: "CASSO_INVALID_PAYLOAD",
};
